[package]
name = "aneurysm"
version = "0.2.0"
description = "Yet Another Brainf**k interpreter"
license = "MIT"
repository = "https://github.com/Oakchris1955/rust-aneurysm"
edition = "2024"
publish = true

[dependencies]
aneurysm-lib = { path = "../aneurysm-lib" }
clap = { workspace = true }
flexi_logger = { workspace = true }
log = { workspace = true }
